### PR TITLE
Fix bug in io_imm: condtions are logically negated but should be reversed

### PR DESCRIPTION
**Pull request by br0ns**

### CODE REVIEW

**Comment by aligrudi** [comment]
Morten Brøns-Pedersen<notifications@github.com> wrote:
> -- Commit Summary --
> 
>   * Fix bug in io_imm: condtions are logically negated but should be reversed

Thanks.  Can you provide a test case for this issue?

**Comment by br0ns** [comment]
Yes:
```
$ cat bug.c
#include <stdio.h>
int main() {
  int a = 1;
  return 1 >= a;
}
$ neatcc/ncc -Ineatlibc bug.c 
$ neatld/nld neatlibc/start.o neatlibc/libc.a bug.o 
$ ./a.out 
$ echo $?
0
$ neatcc/ncc -O0 -Ineatlibc bug.c 
$ neatld/nld neatlibc/start.o neatlibc/libc.a bug.o 
$ ./a.out 
$ echo $?
1
```

**Comment by aligrudi** [comment]
Thanks.  All five patches merged (with minor changes).
However, I do not know how to mark them so in GitHub
via email.

**Comment by br0ns** [comment]
Cool, thanks.  Looks like Github figured out that I participated in your latest commits.  Closing the PRs.  BTW, you have some very... neat... projects.  I checked out `neatcc` because they used it for DEFCON CTF last year.  I've implemented a backend for a toy architecture, and am planning to do a blog post on it.  Would that be OK with you?

**Comment by aligrudi** [comment]
Morten Brøns-Pedersen <notifications@github.com> wrote:
> Cool, thanks.  Looks like Github figured out that I participated in
> your latest commits.  Closing the PRs.  BTW, you have some very...
> neat... projects.  I checked out `neatcc` because they used it for
> DEFCON CTF last year.  I've implemented a backend for a toy
> architecture, and am planning to do a blog post on it.  Would that be
> OK with you?

Certainly.

By the way, when neatcc is compiled with itself (boot target
of neatcc_make), it segfaults when compiling t16.c of the test
suite (this was present before applying your patch).  I don't
know when this issue appeared first.  I shall investigate it
as soon as I find the time.

**Pull request closed without merging**
